[package]
name = "token"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.8.4"
scarb-version = "2.8.4"

[[target.starknet-contract]]
sierra = true

[dependencies]
starknet = "2.8.4"
openzeppelin = "0.18.0"

[dev-dependencies]
