kind = "DojoModel"
class_hash = "0x6d487a9e257063fa50bd2f6331ba3d8d82a62a4851b95802756a0b1b6f4a1de"
original_class_hash = "0x6d487a9e257063fa50bd2f6331ba3d8d82a62a4851b95802756a0b1b6f4a1de"
abi = "manifests/sepoliadev2/base/abis/models/zkube-Participation-7b168a64.json"
tag = "zkube-Participation"
qualified_path = "zkube::models::index::participation"
manifest_name = "zkube-Participation-7b168a64"

[[members]]
name = "chest_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "felt252"
key = true

[[members]]
name = "is_set"
type = "bool"
key = false

[[members]]
name = "points"
type = "u32"
key = false

[[members]]
name = "claimed"
type = "bool"
key = false
