kind = "DojoModel"
class_hash = "0x5f70cc3ff995fbbd09d926feb148fec575a1b9b12b529937473ded65567ffe1"
original_class_hash = "0x5f70cc3ff995fbbd09d926feb148fec575a1b9b12b529937473ded65567ffe1"
abi = "manifests/sepolia/base/abis/models/zkube-Tournament-120c37d1.json"
tag = "zkube-Tournament"
qualified_path = "zkube::models::index::tournament"
manifest_name = "zkube-Tournament-120c37d1"

[[members]]
name = "id"
type = "u64"
key = true

[[members]]
name = "is_set"
type = "bool"
key = false

[[members]]
name = "prize"
type = "u128"
key = false

[[members]]
name = "top1_player_id"
type = "felt252"
key = false

[[members]]
name = "top2_player_id"
type = "felt252"
key = false

[[members]]
name = "top3_player_id"
type = "felt252"
key = false

[[members]]
name = "top1_score"
type = "u32"
key = false

[[members]]
name = "top2_score"
type = "u32"
key = false

[[members]]
name = "top3_score"
type = "u32"
key = false

[[members]]
name = "top1_claimed"
type = "bool"
key = false

[[members]]
name = "top2_claimed"
type = "bool"
key = false

[[members]]
name = "top3_claimed"
type = "bool"
key = false
