kind = "DojoModel"
class_hash = "0x1faf1fb96f5e756885d39feaa8b2777f21845d67c1d5e8df770372173ee62a9"
original_class_hash = "0x1faf1fb96f5e756885d39feaa8b2777f21845d67c1d5e8df770372173ee62a9"
abi = "manifests/sepolia/base/abis/models/zkube-Settings-161104df.json"
tag = "zkube-Settings"
qualified_path = "zkube::models::index::settings"
manifest_name = "zkube-Settings-161104df"

[[members]]
name = "id"
type = "u8"
key = true

[[members]]
name = "is_set"
type = "bool"
key = false

[[members]]
name = "zkorp_address"
type = "felt252"
key = false

[[members]]
name = "free_daily_credits"
type = "u8"
key = false

[[members]]
name = "daily_mode_price"
type = "u128"
key = false

[[members]]
name = "normal_mode_price"
type = "u128"
key = false
