kind = "DojoContract"
class_hash = "0x12b37d078e6ee707b24a3d5e32684bdd0ca0d2afbc569a5b73175b489497115"
original_class_hash = "0x12b37d078e6ee707b24a3d5e32684bdd0ca0d2afbc569a5b73175b489497115"
base_class_hash = "0x0"
abi = "manifests/slotdev/base/abis/contracts/zkube-zkorp-6cdc1046.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-zkorp"
systems = [
    "claim",
    "sponsor",
]
manifest_name = "zkube-zkorp-6cdc1046"
