kind = "DojoModel"
class_hash = "0x1a3488e053dbb77a0bbed2f2074d72a07f898e49c99d9844b53266a91ef3f96"
original_class_hash = "0x1a3488e053dbb77a0bbed2f2074d72a07f898e49c99d9844b53266a91ef3f96"
abi = "manifests/dev/base/abis/models/zkube-Settings-161104df.json"
tag = "zkube-Settings"
qualified_path = "zkube::models::index::settings"
manifest_name = "zkube-Settings-161104df"

[[members]]
name = "id"
type = "u8"
key = true

[[members]]
name = "is_set"
type = "bool"
key = false

[[members]]
name = "zkorp_address"
type = "felt252"
key = false

[[members]]
name = "free_daily_credits"
type = "u8"
key = false

[[members]]
name = "daily_mode_price"
type = "felt252"
key = false

[[members]]
name = "normal_mode_price"
type = "felt252"
key = false
