[world]
name = "zKube"
description = "Reversed tetris fully onchain."
# cover_uri = "file://assets/cover.png"
# icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "zKube8"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"

[namespace]
default = "zkube"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
#rpc_url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"
account_address = "0x0601ecb93c6e88eec432910a2c3ab4d9b5c0dd768b55ab4f8c89336e01fafaa7"

[init_call_args]
"zkube-chest" = ["0x07f599511f57049dd1e5f4f30f893d029c9413095f174f4ffcdb6f0b5ded1a57"]
"zkube-settings" = ["0x0589d37adc1e5cf9ef58da510ee904aa9428d6e9a1c0d5c822392664d063796b", "0x0589d37adc1e5cf9ef58da510ee904aa9428d6e9a1c0d5c822392664d063796b"]
"zkube-tournament" = ["0x07f599511f57049dd1e5f4f30f893d029c9413095f174f4ffcdb6f0b5ded1a57"]
"zkube-zkorp" = ["0x07f599511f57049dd1e5f4f30f893d029c9413095f174f4ffcdb6f0b5ded1a57"]

[writers]
"zkube-Admin" = ["zkube-settings"]
"zkube-Chest" = ["zkube-chest", "zkube-play"]
"zkube-Game" = ["zkube-play"]
"zkube-Mint" = ["zkube-minter"]
"zkube-Participation" = ["zkube-chest", "zkube-play"]
"zkube-Player" = ["zkube-account", "zkube-play"]
"zkube-Settings" = ["zkube-minter", "zkube-settings"]
"zkube-Tournament" = ["zkube-play", "zkube-tournament"]
"zkube-TrophyCreation" = ["zkube-settings"]
"zkube-TrophyProgression" = ["zkube-play"]