kind = "DojoContract"
class_hash = "0x5a4490907f6e7353849dc8b5b7592499c00436d656c98c2d686da6ec21a71ab"
original_class_hash = "0x5a4490907f6e7353849dc8b5b7592499c00436d656c98c2d686da6ec21a71ab"
base_class_hash = "0x0"
abi = "manifests/sepolia/base/abis/contracts/zkube-play-19ee70b3.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-play"
systems = [
    "surrender",
    "move",
    "apply_bonus",
]
manifest_name = "zkube-play-19ee70b3"
