kind = "DojoContract"
class_hash = "0x6f202065370d0ccd384a4f2c545e618f55c25c09ced896d68f7bdc569ba8063"
original_class_hash = "0x6f202065370d0ccd384a4f2c545e618f55c25c09ced896d68f7bdc569ba8063"
base_class_hash = "0x0"
abi = "manifests/sepolia/base/abis/contracts/zkube-account-6d28004d.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-account"
systems = [
    "create",
    "rename",
]
manifest_name = "zkube-account-6d28004d"
