kind = "DojoContract"
class_hash = "0x5dd01fb7c73704470441bfe4b9c9cfd730804a43817f5135bced95d39ea6973"
original_class_hash = "0x5dd01fb7c73704470441bfe4b9c9cfd730804a43817f5135bced95d39ea6973"
base_class_hash = "0x0"
abi = "manifests/slot/base/abis/contracts/zkube-play-19ee70b3.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-play"
systems = [
    "surrender",
    "move",
    "apply_bonus",
]
manifest_name = "zkube-play-19ee70b3"
