kind = "DojoContract"
class_hash = "0x1428ed920a35cc7d1135281a516734db4032fdde52291bbf7c00008c656b109"
original_class_hash = "0x1428ed920a35cc7d1135281a516734db4032fdde52291bbf7c00008c656b109"
base_class_hash = "0x0"
abi = "manifests/slot/base/abis/contracts/zkube-zkorp-6cdc1046.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-zkorp"
systems = [
    "claim",
    "sponsor",
]
manifest_name = "zkube-zkorp-6cdc1046"
