kind = "DojoContract"
class_hash = "0x27e87f8f3658b5b33c91d1c020177f0333bdf3532ed8f3bcdfa544166ff4dd6"
original_class_hash = "0x27e87f8f3658b5b33c91d1c020177f0333bdf3532ed8f3bcdfa544166ff4dd6"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/zkube-settings-3b7c4918.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-settings"
systems = [
    "update_zkorp_address",
    "update_free_daily_credits",
    "update_daily_mode_price",
    "update_normal_mode_price",
    "set_admin",
    "delete_admin",
]
manifest_name = "zkube-settings-3b7c4918"
